version: '3.8'

services:
  fac-csconsts:
    container_name: 'facs-csconsts'
    image: 'ghcr.io/RafaelLyra8/ci_cd:${RELEASE_TAG}'
    build:
      context: .
      labels:
        - "br.com.lnls-sirius.department=FAC"
    ports:
      - 80:80

  fac-csconsts-latest:
    container_name: 'facs-csconsts'
    image: 'ghcr.io/RafaelLyra8/ci_cd'
    build:
      context: .
      labels:
        - "br.com.lnls-sirius.department=FAC"
    ports:
      - 80:80
